job_titles = [
    "Analista de Marketing Digital",
    "Desenvolvedor Front-end",
    "Engenheiro de Software",
    "Gerente de Projetos",
    "Arquiteto de Soluções",
    "Especialista em SEO",
    "Consultor de Vendas",
    "Analista de Dados",
    "Cientista de Dados",
    "Desenvolvedor Back-end",
    "Designer Gráfico",
    "Gerente de Contas",
    "Analista de RH",
    "Coordenador de TI",
    "Analista Financeiro",
    "Gerente de Operações",
    "Técnico de Suporte",
    "Engenheiro de DevOps",
    "Desenvolvedor Mobile",
    "Analista de Segurança da Informação",
    "Especialista em Redes",
    "Gerente de Produto",
    "Analista de Business Intelligence",
    "Consultor de Marketing",
    "Especialista em Cloud",
    "Engenheiro de Dados",
    "Analista de Sistemas",
    "Desenvolvedor Full Stack",
    "Analista de Suporte Técnico",
    "Coordenador de Projetos",
    "Analista de Qualidade",
    "Engenheiro de Testes",
    "Especialista em Infraestrutura",
    "Designer UX/UI",
    "Arquiteto de Software",
    "Consultor de Negócios",
    "Analista de Comunicação",
    "Gerente de Recursos Humanos",
    "Coordenador de Logística",
    "Analista de Compras",
    "Desenvolvedor de Jogos",
    "Analista de Marketing de Conteúdo",
    "Especialista em E-commerce",
    "Consultor de TI",
    "Analista de CRM",
    "Gerente de Desenvolvimento",
    "Analista de Processos",
    "Engenheiro de Redes",
    "Desenvolvedor Python",
    "Analista de Performance",
    "Consultor de Segurança da Informação",
    "Coordenador de Atendimento",
    "Analista de Trade Marketing",
    "Gerente de TI",
    "Desenvolvedor Java",
    "Especialista em Inteligência Artificial",
    "Analista de Logística",
    "Designer de Produto",
    "Consultor de RH",
    "Gerente de Marketing",
    "Analista de Mídias Sociais",
    "Engenheiro de Software Sênior",
    "Analista de Projetos",
    "Desenvolvedor PHP",
    "Especialista em Machine Learning",
    "Consultor de Negócios Digitais",
    "Gerente de Segurança da Informação",
    "Analista de Infraestrutura",
    "Engenheiro de Sistemas",
    "Desenvolvedor C++",
    "Analista de Produção",
    "Consultor de Comunicação",
    "Coordenador de Suporte Técnico",
    "Analista de Pricing",
    "Desenvolvedor Ruby",
    "Especialista em Automação",
    "Consultor de Cloud",
    "Gerente de Vendas",
    "Analista de E-commerce",
    "Engenheiro de Computação",
    "Desenvolvedor .NET",
    "Analista de Riscos",
    "Consultor de Gestão",
    "Coordenador de Qualidade",
    "Analista de Testes",
    "Desenvolvedor de Aplicativos",
    "Especialista em Transformação Digital",
    "Consultor de Performance",
    "Gerente de Projetos Ágeis",
    "Analista de Segurança",
    "Engenheiro de Aplicações",
    "Desenvolvedor React",
    "Analista de BI",
    "Consultor de Desenvolvimento",
    "Coordenador de Desenvolvimento",
    "Analista de Negócios",
    "Desenvolvedor Node.js",
    "Especialista em IoT",
    "Consultor de Inovação",
    "Gerente de Serviços",
    "Analista de Controle de Qualidade",
    "Engenheiro de Infraestrutura",
    "Desenvolvedor Angular",
    "Analista de TI",
    "Consultor de Projetos",
    "Coordenador de Infraestrutura",
    "Analista de Implementação",
    "Desenvolvedor SQL",
    "Especialista em Sistemas",
    "Consultor de Tecnologia",
    "Gerente de Implementação",
    "Analista de Governança",
    "Engenheiro de Automação",
    "Desenvolvedor iOS",
    "Analista de Contabilidade",
    "Consultor de Serviços",
    "Coordenador de Desenvolvimento de Software",
    "Analista de Relacionamento",
    "Desenvolvedor Android",
    "Especialista em Big Data",
    "Consultor de Infraestrutura",
    "Gerente de Arquitetura",
    "Analista de Processos de Negócios",
    "Engenheiro de Produção",
    "Desenvolvedor Salesforce",
    "Analista de Negócios Digitais",
    "Consultor de BI",
    "Coordenador de Segurança da Informação",
    "Analista de Configuração",
    "Desenvolvedor JavaScript",
    "Especialista em UX",
    "Consultor de Arquitetura de TI",
    "Gerente de Integração",
    "Analista de Sustentabilidade",
    "Engenheiro de Qualidade",
    "Desenvolvedor Web",
    "Analista de Pesquisa de Mercado",
    "Consultor de Vendas Técnicas",
    "Coordenador de CRM",
    "Analista de Documentação",
    "Desenvolvedor de APIs",
    "Especialista em Virtualização",
    "Consultor de Treinamento",
    "Gerente de Desenvolvimento de Sistemas",
    "Analista de Recursos Humanos",
    "Engenheiro de Field Service",
    "Desenvolvedor de Banco de Dados",
    "Analista de Supply Chain",
    "Consultor de Processos",
    "Coordenador de Melhoria Contínua",
    "Analista de Contratos",
    "Desenvolvedor de Blockchain",
    "Especialista em Processos",
    "Consultor de Estratégia",
    "Gerente de Planejamento",
    "Analista de Suporte ao Cliente",
    "Engenheiro de Suporte",
    "Desenvolvedor de Chatbots",
    "Analista de Transformação Digital",
    "Consultor de Otimização",
    "Coordenador de Suporte ao Cliente",
    "Analista de Indicadores",
    "Desenvolvedor de Microserviços",
    "Especialista em Arquitetura de Software",
    "Consultor de Qualidade",
    "Gerente de Mobilidade",
    "Analista de Prospecção de Clientes",
    "Engenheiro de Energia",
    "Desenvolvedor de Sistemas Embarcados",
    "Analista de Gestão de Projetos",
    "Consultor de Engenharia de Software",
    "Coordenador de Compliance",
    "Analista de Cadastro",
    "Desenvolvedor de Realidade Aumentada",
    "Especialista em Gestão de Projetos",
    "Consultor de Operações",
    "Gerente de Tecnologia da Informação",
    "Analista de Integração de Sistemas",
    "Engenheiro de Segurança",
    "Desenvolvedor de Realidade Virtual",
    "Analista de P&D",
    "Consultor de Gestão de Mudanças",
    "Coordenador de Inovação",
    "Analista de Suporte a Sistemas",
    "Desenvolvedor de Softwares Corporativos",
    "Especialista em Gestão de Pessoas",
    "Consultor de Processos Industriais",
    "Gerente de Cibersegurança",
    "Analista de TI Pleno",
    "Engenheiro de Telecomunicações",
    "Desenvolvedor de Sistemas Corporativos",
    "Analista de Mobilidade",
    "Consultor de Automação de Processos",
    "Coordenador de Segurança de Redes",
    "Analista de Operações",
    "Desenvolvedor de Softwares de Segurança",
    "Especialista em Gestão de TI",
    "Consultor de Arquitetura Corporativa",
    "Gerente de Infraestrutura de TI",
    "Analista de Tecnologia",
    "Engenheiro de Integração",
    "Desenvolvedor de Aplicações de Segurança",
    "Analista de Desenvolvimento de Sistemas",
    "Consultor de Engenharia de Dados",
    "Coordenador de Projetos de TI",
    "Analista de Sistemas Sênior",
    "Desenvolvedor de Sistemas IoT",
    "Especialista em Desenvolvimento de Software",
    "Consultor de Gestão de Riscos",
    "Gerente de Desenvolvimento de Produtos",
    "Analista de Negócios de TI",
    "Engenheiro de Controle de Qualidade",
    "Desenvolvedor de Aplicações Corporativas",
    "Analista de Soluções Digitais",
    "Consultor de Desenvolvimento de Sistemas",
    "Coordenador de Desenvolvimento de Produtos",
    "Analista de Inteligência de Mercado",
    "Desenvolvedor de Aplicações Web",
    "Especialista em Automação de Testes",
    "Consultor de Gestão Empresarial",
    "Gerente de Soluções Tecnológicas"
]

professional_experiences = [
    "Responsável pelo desenvolvimento de estratégias de marketing digital, resultando em um aumento de 30% no engajamento nas redes sociais.",
    "Gerenciamento de projetos de software, garantindo a entrega pontual e dentro do orçamento.",
    "Desenvolvimento e manutenção de aplicações web utilizando tecnologias como HTML, CSS e JavaScript.",
    "Coordenação de equipes multidisciplinares para a implementação de soluções de TI.",
    "Análise de dados e criação de relatórios para apoiar a tomada de decisões estratégicas.",
    "Desenvolvimento de algoritmos de machine learning para melhorar a precisão das previsões de vendas.",
    "Implementação de sistemas de segurança da informação para proteger dados sensíveis.",
    "Criação de campanhas de e-mail marketing que geraram um aumento de 25% nas conversões.",
    "Desenvolvimento de aplicativos móveis para plataformas iOS e Android.",
    "Gerenciamento de infraestrutura de TI, incluindo servidores e redes.",
    "Coordenação de processos de recrutamento e seleção, resultando na contratação de profissionais qualificados.",
    "Desenvolvimento de estratégias de SEO que aumentaram o tráfego orgânico em 40%.",
    "Análise de mercado e identificação de oportunidades de crescimento.",
    "Desenvolvimento de interfaces de usuário intuitivas e funcionais.",
    "Gerenciamento de operações logísticas para otimizar a eficiência e reduzir custos.",
    "Implementação de sistemas ERP para melhorar a gestão de recursos empresariais.",
    "Desenvolvimento de soluções em nuvem para aumentar a escalabilidade e flexibilidade dos serviços.",
    "Análise e melhoria de processos de negócios para aumentar a produtividade.",
    "Desenvolvimento de jogos utilizando motores gráficos como Unity e Unreal Engine.",
    "Gestão de projetos ágeis utilizando metodologias Scrum e Kanban.",
    "Análise de performance de campanhas publicitárias e otimização de resultados.",
    "Desenvolvimento de sistemas de controle de qualidade para garantir a excelência dos produtos.",
    "Implementação de soluções de big data para análise de grandes volumes de informações.",
    "Desenvolvimento de APIs RESTful para integração de sistemas.",
    "Coordenação de atividades de suporte técnico para resolver problemas de usuários.",
    "Desenvolvimento de chatbots utilizando técnicas de processamento de linguagem natural.",
    "Análise de riscos e desenvolvimento de planos de mitigação.",
    "Desenvolvimento de sistemas de automação para aumentar a eficiência operacional.",
    "Gestão de relacionamento com clientes para garantir a satisfação e fidelização.",
    "Desenvolvimento de estratégias de marketing de conteúdo para aumentar a visibilidade da marca.",
    "Implementação de soluções de business intelligence para análise de dados.",
    "Desenvolvimento de testes automatizados para garantir a qualidade do software.",
    "Coordenação de projetos de inovação para desenvolvimento de novos produtos.",
    "Análise de desempenho de redes e otimização de infraestrutura de TI.",
    "Desenvolvimento de sistemas de pagamento online seguros e eficientes.",
    "Gestão de contratos com fornecedores e parceiros.",
    "Implementação de estratégias de transformação digital para modernizar processos empresariais.",
    "Desenvolvimento de soluções de inteligência artificial para automação de tarefas.",
    "Análise de indicadores de desempenho e elaboração de relatórios gerenciais.",
    "Desenvolvimento de soluções de e-commerce para aumentar as vendas online.",
    "Coordenação de atividades de compliance para garantir a conformidade com regulamentações.",
    "Implementação de políticas de segurança cibernética para proteger sistemas e dados.",
    "Desenvolvimento de dashboards interativos para visualização de dados.",
    "Gestão de equipes de desenvolvimento de software para garantir a entrega de projetos.",
    "Desenvolvimento de sistemas de gestão de conteúdo para sites e aplicativos.",
    "Análise de tendências de mercado e identificação de oportunidades de inovação.",
    "Desenvolvimento de soluções de realidade aumentada e virtual para diversas aplicações.",
    "Coordenação de atividades de treinamento e desenvolvimento de funcionários.",
    "Implementação de estratégias de governança de TI para melhorar a gestão de recursos.",
    "Desenvolvimento de sistemas de automação de marketing para aumentar a eficiência das campanhas.",
    "Análise de feedback de clientes e desenvolvimento de planos de ação para melhorias.",
    "Desenvolvimento de soluções de blockchain para aumentar a segurança e transparência.",
    "Coordenação de atividades de desenvolvimento de produto para atender às necessidades do mercado.",
    "Implementação de estratégias de gerenciamento de mudanças para garantir a adoção de novas tecnologias.",
    "Desenvolvimento de soluções de integração de sistemas para aumentar a eficiência operacional.",
    "Análise de dados de vendas e desenvolvimento de estratégias para aumentar a receita.",
    "Desenvolvimento de soluções de Internet das Coisas (IoT) para diversos setores.",
    "Coordenação de atividades de planejamento estratégico para alcançar os objetivos empresariais.",
    "Implementação de estratégias de experiência do cliente para aumentar a satisfação.",
    "Desenvolvimento de sistemas de gestão de projetos para melhorar a eficiência e controle.",
    "Análise de dados financeiros e desenvolvimento de relatórios para a diretoria.",
    "Desenvolvimento de soluções de automação industrial para aumentar a produtividade.",
    "Coordenação de atividades de marketing digital para aumentar a presença online.",
    "Implementação de estratégias de gestão de talentos para atrair e reter profissionais qualificados.",
    "Desenvolvimento de soluções de software para automação de processos empresariais.",
    "Análise de performance de sistemas e desenvolvimento de planos de otimização.",
    "Desenvolvimento de soluções de telemetria para monitoramento remoto de ativos.",
    "Coordenação de atividades de suporte a clientes para resolver problemas técnicos.",
    "Implementação de estratégias de redução de custos para aumentar a rentabilidade.",
    "Desenvolvimento de soluções de análise preditiva para melhorar a tomada de decisões.",
    "Análise de dados de mercado e desenvolvimento de estratégias de entrada.",
    "Desenvolvimento de soluções de monitoramento em tempo real para diversos setores.",
    "Coordenação de atividades de melhoria contínua para aumentar a eficiência operacional.",
    "Implementação de estratégias de marketing de influência para aumentar a visibilidade da marca.",
    "Desenvolvimento de soluções de segurança para proteger redes e sistemas.",
    "Análise de dados de desempenho de campanhas publicitárias e otimização de resultados.",
    "Desenvolvimento de soluções de inteligência competitiva para monitorar o mercado.",
    "Coordenação de atividades de gestão de projetos para garantir a entrega dentro do prazo.",
    "Implementação de estratégias de gestão de riscos para minimizar impactos negativos.",
    "Desenvolvimento de soluções de análise de sentimentos para monitorar a reputação online.",
    "Análise de dados de produção e desenvolvimento de estratégias de otimização.",
    "Desenvolvimento de soluções de gerenciamento de ativos para aumentar a eficiência.",
    "Coordenação de atividades de pesquisa e desenvolvimento para inovação de produtos.",
    "Implementação de estratégias de gestão de conhecimento para melhorar a transferência de informações.",
    "Desenvolvimento de soluções de automação de testes para garantir a qualidade do software.",
    "Análise de dados de inventário e desenvolvimento de estratégias de otimização.",
    "Desenvolvimento de soluções de análise de dados para suportar a tomada de decisões.",
    "Coordenação de atividades de gestão de mudanças para garantir a adoção de novas tecnologias.",
    "Implementação de estratégias de gerenciamento de incidentes para minimizar interrupções.",
    "Desenvolvimento de soluções de análise de comportamento do consumidor para aumentar as vendas.",
    "Análise de dados de desempenho de produtos e desenvolvimento de planos de melhoria.",
    "Desenvolvimento de soluções de análise de crédito para minimizar riscos financeiros.",
    "Coordenação de atividades de gestão de projetos ágeis para aumentar a eficiência.",
    "Implementação de estratégias de transformação digital para modernizar processos empresariais.",
    "Desenvolvimento de soluções de inteligência artificial para automação de tarefas.",
    "Análise de indicadores de desempenho e elaboração de relatórios gerenciais.",
    "Desenvolvimento de soluções de e-commerce para aumentar as vendas online.",
    "Coordenação de atividades de compliance para garantir a conformidade com regulamentações.",
    "Implementação de políticas de segurança cibernética para proteger sistemas e dados.",
    "Desenvolvimento de dashboards interativos para visualização de dados.",
    "Gestão de equipes de desenvolvimento de software para garantir a entrega de projetos.",
    "Desenvolvimento de sistemas de gestão de conteúdo para sites e aplicativos.",
    "Análise de tendências de mercado e identificação de oportunidades de inovação.",
    "Desenvolvimento de soluções de realidade aumentada e virtual para diversas aplicações.",
    "Coordenação de atividades de treinamento e desenvolvimento de funcionários.",
    "Implementação de estratégias de governança de TI para melhorar a gestão de recursos.",
    "Desenvolvimento de sistemas de automação de marketing para aumentar a eficiência das campanhas.",
    "Análise de feedback de clientes e desenvolvimento de planos de ação para melhorias.",
    "Desenvolvimento de soluções de blockchain para aumentar a segurança e transparência.",
    "Coordenação de atividades de desenvolvimento de produto para atender às necessidades do mercado.",
    "Implementação de estratégias de gerenciamento de mudanças para garantir a adoção de novas tecnologias.",
    "Desenvolvimento de soluções de integração de sistemas para aumentar a eficiência operacional.",
    "Análise de dados de vendas e desenvolvimento de estratégias para aumentar a receita.",
    "Desenvolvimento de soluções de Internet das Coisas (IoT) para diversos setores.",
    "Coordenação de atividades de planejamento estratégico para alcançar os objetivos empresariais.",
    "Implementação de estratégias de experiência do cliente para aumentar a satisfação.",
    "Desenvolvimento de sistemas de gestão de projetos para melhorar a eficiência e controle.",
    "Análise de dados financeiros e desenvolvimento de relatórios para a diretoria.",
    "Desenvolvimento de soluções de automação industrial para aumentar a produtividade.",
    "Coordenação de atividades de marketing digital para aumentar a presença online.",
    "Implementação de estratégias de gestão de talentos para atrair e reter profissionais qualificados.",
    "Desenvolvimento de soluções de software para automação de processos empresariais.",
    "Análise de performance de sistemas e desenvolvimento de planos de otimização.",
    "Desenvolvimento de soluções de telemetria para monitoramento remoto de ativos.",
    "Coordenação de atividades de suporte a clientes para resolver problemas técnicos.",
    "Implementação de estratégias de redução de custos para aumentar a rentabilidade.",
    "Desenvolvimento de soluções de análise preditiva para melhorar a tomada de decisões.",
    "Análise de dados de mercado e desenvolvimento de estratégias de entrada.",
    "Desenvolvimento de soluções de monitoramento em tempo real para diversos setores.",
    "Coordenação de atividades de melhoria contínua para aumentar a eficiência operacional.",
    "Implementação de estratégias de marketing de influência para aumentar a visibilidade da marca.",
    "Desenvolvimento de soluções de segurança para proteger redes e sistemas.",
    "Análise de dados de desempenho de campanhas publicitárias e otimização de resultados.",
    "Desenvolvimento de soluções de inteligência competitiva para monitorar o mercado.",
    "Coordenação de atividades de gestão de projetos para garantir a entrega dentro do prazo.",
    "Implementação de estratégias de gestão de riscos para minimizar impactos negativos.",
    "Desenvolvimento de soluções de análise de sentimentos para monitorar a reputação online.",
    "Análise de dados de produção e desenvolvimento de estratégias de otimização.",
    "Desenvolvimento de soluções de gerenciamento de ativos para aumentar a eficiência.",
    "Coordenação de atividades de pesquisa e desenvolvimento para inovação de produtos.",
    "Implementação de estratégias de gestão de conhecimento para melhorar a transferência de informações.",
    "Desenvolvimento de soluções de automação de testes para garantir a qualidade do software.",
    "Análise de dados de inventário e desenvolvimento de estratégias de otimização.",
    "Desenvolvimento de soluções de análise de dados para suportar a tomada de decisões.",
    "Coordenação de atividades de gestão de mudanças para garantir a adoção de novas tecnologias.",
    "Implementação de estratégias de gerenciamento de incidentes para minimizar interrupções.",
    "Desenvolvimento de soluções de análise de comportamento do consumidor para aumentar as vendas.",
    "Análise de dados de desempenho de produtos e desenvolvimento de planos de melhoria.",
    "Desenvolvimento de soluções de análise de crédito para minimizar riscos financeiros.",
    "Coordenação de atividades de gestão de projetos ágeis para aumentar a eficiência."
]